### ISSUE TITLE
Correct information about Clover

### ISSUE THREAD

**Issue by midi1996** [macfanatic77/hackintosh#1]
In your guide in this part https://github.com/macfanatic77/hackintosh/blob/master/00_Basics%20of%20the%20Vanilla%20Method.md#what-is-clover

1) The EFI partition is not "built" by anything, the moment when you select GUID Partition Table (GPT) in Disk Utility, macOS will create a 200MB FAT32 partition in the beginning of the disk and the rest will be for whatever partitioning you added, this is somehow a requirement for HFS+ but not for GPT (macOS is stupid, as is HFS+).
2) Clover Configurator (note that it is not affiliated with Clover at all, it's an independent project from Clover Boot Manager) is a good choice for beginners, but I recommend you to use the manual methods of mounting the EFI and configuring your setup later on (Clover Configurator can't yet set "FALSE" value in some entries and that's frustrating and also may break your config if it crashes, use a Plist Editor (like the one in Xcode, Clover Configurator Pro or a simple text editor)
3) The path of config.plist isnt in /EFI/Clover, but in /EFI/<your ESP's name> (and ESP means EFI System Partition, basically your EFI partition, and it has a name/label, and that's where it's shown)

What I would say at this part is:
1) Clover is a "Boot Manager" rather than a bootloader, as Clover loads "boot.efi" found in macOS's partition which is the real bootloader of macOS
2) Clover is the one that injects the information from the config.plist (like SMBIOS, boot arguments...) and your ACPI > patched files (if any) and kexts into your system.
3) Clover can be used with any OS, it's not macOS restricted, but it has more options offered on the macOS side than other OSes
4) Clover is **installed** in a FAT32 partition if you're booting it in a UEFI system, reason: UEFI systems (most of them anyways) can only mount and read data from FAT32 partition, and usually the ESP (EFI System Partition) is FAT32 (and flagged as EF00), and so when you install clover to the ESP, the installer pkg will mount your ESP, copy clover files in, and it's up to you to configure it.
5) Clover may need "drivers" and they're UEFI Drivers and **they have nothing to do with** macOS drivers (kexts), and these drivers will help clover load partition (HFSPlus, VboxHfs, ApfsDriverLoader...), fix firmware issues that macOS complains from (AptioMemoryFix, OsxAptioFixDrv...) and other extras. Clover doesnt need them for its basic functioning, but will if you need extra functionalities.
6) Clover has a configuration file named "config.plist" which is a [plist file](https://en.wikipedia.org/wiki/Property_list) and contains information that clover needs to inject, show menus, apply patches, apply fixes, load things ... it has a similar format as XML, and can be edited with many tools like Xcode (plist editor), TextEdit, Clover Configurator Pro, Clover Configurator Global and so on, note that none of these are affiliated with Clover.

**Comment by macfanatic77** [comment]
Agreed. I simply documented things as I was learning from all sorts of valid (and sometimes questionable) sources so it's always wonderful to have correct information. I've updated that section and credited you. Thank you again.
