### ISSUE TITLE
Some Extra fixes

### ISSUE THREAD

**Issue by midi1996** [macfanatic77/hackintosh#2]
https://github.com/macfanatic77/hackintosh/blob/master/05_Clover_Builder_and_Configurator.md#usb

You do not have to route your USB port to EHCI, ever since Skylake (100-series boards), intel remove the EHCI controller from their motherboards, and this will leave you with XHCI, if your motherboard has USB2.0 port, they're either connected to the xHCI controller but only have the HS (USB2.0) pins working, or to another non-Intel controller. I dont think Z390 would go back and use EHCI on their motherboards, so they also dont need FakePCIID + XHCIMux.

Also remove SMCBatteryManager (I believe your desktop doesnt have a battery, does it?) and SMCLightSensor (I dont think you have one, it's mostly on laptops).
GenericUSBXHCI I dont believe it's needed but I dont have the hardware to confirm, usually it's needed on Xtreme motherboards (as they also have some USB headers used by 3rd party USB controllers other than intel's).
As for why your USB-C doesnt work, this is a quite known on some motherboards and laptops, your USB-C is a Gen2, so it's not connected to the USB controller at all! it has its own controller (usually) and it's probably not defined in your ACPI, and so macOS cannot utilize it (my ThinkPad P50 had the same issue and I had to manually define the USB-C device). You can check this https://github.com/syscl/XPS9350-macOS/issues/33. If you need me to check with you if it's possible to fix this (idk if it is for your case, but it did work for 3 devices I helped with and mine). I'm available in the Discord server (midi#4911).

**Comment by macfanatic77** [comment]
Damn, you are amazing. Thank you! I will take a look at the post you linked. In the meantime, I have edited and corrected my guide to reflect your thoughts. Thank you!
